



export class GlobalVariables {
  static jobFields = [
    "Administration / Secretarial / Personal Assistant (PA) / Clerical / Office Assistant",
    "Advertising / Branding / Public Relation (PR)",
    "Agriculture / Agro-Allied / Farming",
    "Architectural / Designing / Surveying",
    "Artisan / Labour / Factory Work / Craftsmen / Vocational / Semi-Skilled",
    "Arts / Craft / Creatives",
    "Automobile Services / Car Painting / Car Mechanic / Car Electrician / Car Panel Beater / Car Upholstery",
    "Aviation / Airline Services / Air Hostess / Pilot / Captain / Aircraft Engineer",
    "Biological Sciences - Biochemistry / Microbiology / Plant Science / Environmental",
    "Caregiver / Nanny / Domestic Help",
    "Cashiers / Tellers / Ticketing",
    "Chaplain / Pastoral / Reverend / Ministration",
    "Cleaning / Janitorial / Laundry",
    "Computer",
    "Computer / Cloud Computing / Data Warehousing / Amazon Web Services (AWS)",
    "Computer / Database Support / Database Admin / Database Development / Oracle / MySQL",
    "Computer / Frontend Design / UI / UX / Frontend Scripting / Javascript / React / JQuery",
    "Computer / Full Stack Software Development / Frontend & Backend / Web Design & Development",
    "Computer / Graphics Design / Artist",
    "Computer / Mobile App Development / Android / IOS / Games / React Native / Flutter",
    "Computer / Network & Hardware Engineering Support / Network Design and Security",
    "Computer / System Admin / Software Support / Windows Admin / Linux Admin",
    "Consulting / Business Strategy / Planning",
    "Cook / Chef / Baker / Pastry Chef / Steward",
    "Customer Service / Call Centre / Front Desk / Receptionist",
    "Data Entry / Analysis",
    "Digital Marketing / Social Media Management",
    "Driving / Haulage / Dispatch Rider / Bike Rider / Chauffeur",
    "Economics / Statistics / Data Science",
    "Education - Higher Institution / Teaching / Lecturing / Training",
    "Education - Non Academic / Registrar / Bursary / Admin / Librarian",
    "Education - Sec/Pri/Creche / Teaching / Tutoring / Creche Services",
    "Election Personnel / Ad-hoc Officers",
    "Engineering",
    "Engineering - Biomedical Engineering",
    "Engineering - Chemical / Petroleum / Petrochemical",
    "Engineering - Civil / Construction / Building",
    "Engineering - Electrical / Electronics / Telecom",
    "Engineering - Mechanical / Metallurgical / Mechatronics",
    "Environmental Services",
    "Executive / Top Management",
    "Facility Management / Estate Management / Maintenance",
    "Fashion Design / Beauty Care / Make-up / Tailoring / Hair Stylist",
    "Finance / Accounting / Audit / Tax",
    "Food & Nutrition / Dietetics / Food Technology",
    "Furniture Design / Carpentery",
    "Graduate Trainee / Fresh Graduate / Graduate Internship",
    "Horticulture / Beautification / Gardening",
    "Hospitality / Travel & Tourism / Hotel / Restuarant / Catering / Museum / Club / Bar / Tour Guide",
    "HSE / Safety & Risk Management / Compliance",
    "Human Resources / Recruitment",
    "Insurance / Assurance / Actuary",
    "Internship / SIWES / Industrial Training",
    "Language Translation / Transcribing / Interpreting",
    "Law / Legal",
    "Logistics / Procurement / Purchasing / Supply Chain",
    "Maritime Services / Shipping / Clearing & Forwarding / Marine Officer / Seamen",
    "Marketing / Sales / Business Development / Merchandiser",
    "Media / Broadcasting / Journalism / Content Writing / Editing",
    "Medical",
    "Medical - Anatomy / Physiology / Pathology / Basic Medical Science",
    "Medical - Dental / ENT",
    "Medical - Health Information / Medical Records / Health Management",
    "Medical - Nursing & Midwifery",
    "Medical - Optometrist / Ophtalmologist",
    "Medical - Pharmaceutical",
    "Medical - Physician / Medical Officer / Doctor / Consultants / Medical Internship",
    "Medical - Physiotherapy / Massage Therapy / Masseuse / Masseur",
    "Medical - Public Health Worker / Hospital Attendant / Orderly",
    "Medical - Veterinary Medicine",
    "Medical Laboratory / Radiography / Sonography",
    "Modelling / Ushering Services / Runway Services",
    "Monitoring and Evaluation / Social Worker",
    "Multimedia / Film Production / Photograhpy / Cinematography / Video & Audio Edtiting",
    "Music Entertainment / Comedy / Disc Jockey (DJ) / Master of Ceremony (MC)",
    "Operations / Project Management",
    "Physical Sciences - Chemistry / Physics / Geography / Earth Science (Geology) / Material Science / Astronomy",
    "Psychology / Clinical Psychology",
    "Quality Assurance (QA) / Quality Control (QC)",
    "Remote / Freelance / Work at home",
    "Research / Survey",
    "Scholarship / Grant / Competition",
    "Security - Guard / Gateman",
    "Security - Military / Police / Civil Defence / Para-Military",
    "Security - Professional / Public / Corporate Security Management",
    "Sports / Fitness / Gym Instructor",
    "Store-Keeping & Warehousing",
    "Technician - Electrical / Electrician",
    "Technician - Fitter / Plumber / Welder / Panel Beater / Scaffolder",
    "Technician - Mechanical / Mechanic / Generator Technician",
    "Tender / Bid / Quotation / Proposal / Expression of Interest",
    "Waiter / Waitress / Concierge / Room Attendant",
  ];
  static jobRoles = [
    "Accountant / Accounting",
    "Agricultural Scientist",
    "Air Conditioner Installer",
    "Android / iOS / Mobile Developer",
    "ASP / .Net Developer",
    "Audio Editor",
    "Auditor / Auditing",
    "Baker / Pastry Chef",
    "Barber",
    "Bartender / Barman / Cocktail Mixer",
    "Beauty Care",
    "Biological Scientist",
    "Business Administration",
    "Business Development",
    "Butcher",
    "Call Centre Executive",
    "Carpenter",
    "Cashier / Teller",
    "Caterer",
    "Chemical Engineer",
    "Cinematographer / Camera Operator",
    "Cisco Network Engineer",
    "Civil Engineer",
    "Cleaner / Janitor / Porter",
    "Clearing & Forwarding / Customs Clearing Agent",
    "Clerk / Clerical Officer",
    "Computer Engineer",
    "Computer Network Engineer",
    "Cook / Chef",
    "Customer Service",
    "Data Entry Officer",
    "Database Administrator",
    "Dentist",
    "Derrick Man",
    "Digital Marketer",
    "Dispatch Rider",
    "Driver (Car / Bus / Truck)",
    "Economist",
    "Electrical Electronics Engineer",
    "Entertainer",
    "Facility Manager / Officer / Executive",
    "Factory Worker",
    "Farmer",
    "Farming / Agro-Allied",
    "Fish Farmer",
    "Fitter",
    "Food Scientist / Technologist",
    "Front Desk Officer",
    "Front-End Developer and UI/UX Designer",
    "Gardener",
    "Geologist",
    "Graphic Designer",
    "Gym & Fitness Instructor",
    "Hair Stylist",
    "Health Scientist",
    "Hospitality Manager / Supervisor - Hotel / Restuarant / Club / Bar / Tourist Center / Event Center",
    "Hotelier",
    "House Maid / House Help",
    "Human Resources",
    "Iron Bender",
    "Java Developer",
    "Journalist",
    "Land Surveyor",
    "Laundry Man / Attendant",
    "Lecturer",
    "Legal Practitioner / Lawyer",
    "Librarian",
    "Linux Administrator",
    "Logistics / Purchasing / Supply",
    "Machine Operator",
    "Maintenance Officer",
    "Maintenance Technician",
    "Make-up Artist",
    "Marine Officer",
    "Marketer",
    "Mason",
    "Massage Therapist / Masseur",
    "Mechanical Engineer",
    "Medical Laboratory Scientist / Technician",
    "Medical Officer / Practitioner / Doctor",
    "Merchandiser",
    "Microsoft SQL Server Administrator",
    "Military Officer",
    "Monitoring and Evaluation",
    "MySQL Administrator",
    "Nail Technician",
    "Nanny / Caregiver",
    "Network Engineer",
    "Nurse / Midwife",
    "Office Assistant",
    "On Air Personality / OAP",
    "Operations / Project Management",
    "Optometrist / Ophthalmologist",
    "Oracle Administrator",
    "Oracle Developer",
    "Panel Beater",
    "Pastor / Chaplain",
    "Personal Assistant",
    "Petroluem Engineer",
    "Pharmacist",
    "Pharmacy Technician",
    "Photographer",
    "PHP / MySQL Developer",
    "Physical / Applied Scientist",
    "Physiotherapist",
    "Pilot",
    "Plumber",
    "Poultry Farmer",
    "Presenter",
    "Programmer / Full Stack Developer",
    "Public Administration",
    "Public Health",
    "Public Relations Executive / PR",
    "Quality Assurance Officer",
    "Quantity Surveyor",
    "Radio Operator",
    "Remote / Freelance / Work at home",
    "Researcher",
    "Room Attendant / Concierge",
    "Safety & Health / HSE",
    "Sales",
    "Scaffolder",
    "Seamen",
    "Secretary",
    "Security Guard",
    "Social Media Specialist / Manager",
    "Sonographer / Radiographer",
    "Statistics / Statistician",
    "Stylist",
    "System Administrator",
    "Tailor / Fashion Designer",
    "Teacher / Tutor / Trainer",
    "Tour Guide",
    "Trainee",
    "TV Operator",
    "Video Editor",
    "Visual Basic / Studio Developer",
    "Volunteer",
    "Waiter / Waitress",
    "Warehouse / Store keeper",
    "Web Designer",
    "Web Developer",
    "Welder",
    "Windows Developer",
    "Writer / Editor",
  ];
  static states = [
    "Abia",
    "Abuja (FCT)",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "Gombe",
    "Imo",
    "Jagawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nassarawa",
    "Niger",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara",
  ];
  static days = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
  static months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ];

  static jobTypes = [

  "Full-time",
  "Part-time",
  "Contract",
  "Temporary",
  "Internship",
  "Freelance",
  "Per Diem",
  "Seasonal",

  "Remote",
  "On-site",
  "Hybrid",

  "Day Shift",
  "Night Shift",
  "Weekend Shift",
  "Flexible Hours",
  "Rotational Shift",

  "Entry-Level",
  "Mid-Level",
  "Senior-Level",
  "Manager",
  "Director",
  "Executive",

  "Volunteer",
  "Apprenticeship",
  "Commission-Based",
  "Gig"
];

}
